spring:
  config:
    import:
      - "classpath:kafka.yml"
      - "classpath:email.yml"
  datasource:
    url: jdbc:postgresql://localhost:5432/homework
    username: testuser
    password: 123
    driver-class-name: org.postgresql.Driver
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: messages

logging:
  level:
    org.springframework.boot: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

