spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homework
    username: testuser
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: messages

logging:
  level:
    root: INFO
