FROM maven:3.9.9-eclipse-temurin-17 AS builder

WORKDIR /build

COPY pom.xml .

COPY common ./common
COPY api-gateway ./api-gateway
COPY user-service ./user-service
COPY notification-service ./notification-service
COPY config-server ./config-server
COPY discovery-service ./discovery-service

RUN mvn dependency:go-offline -B

RUN mvn clean package -DskipTests -pl user-service -am

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=builder /build/user-service/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
