FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /build
COPY . .
RUN mvn clean package -DskipTests -pl notification-service -am

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /build/notification-service/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]