spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/homework
    username: testuser
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092