spring:
  mail:
    host: smtp.yandex.ru
    port: 587
    username: teamhomework@yandex.ru
    password: ulcpdwaaxtshstcg
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    test-connection: true

email:
  sender: teamhomework@yandex.ru
  reply-to: teamhomework@yandex.ru